SERVICE_PATH=/etc/systemd/system

all: {% for container in containers %} {{ container.name }} {% endfor %}

help:
	@echo "USAGE: make TARGET [TARGET...]"
	@echo "Targets:"
	@echo -e "   help\t\t\tDisplay this help message"
	@echo -e "   all (default)\tCreate and start containers"
	@echo -e "   list\t\t\tList containers"
	@echo -e "   start\t\tStart containers"
	@echo -e "   stop\t\t\tStop containers"
	@echo -e "   install\t\tInstall systemd service files for containers"
	@echo -e "   enable\t\tEnable systemd service files for containers"
	@echo -e "   disable\t\tDisable systemd service files for containers"
	@echo -e "   clean\t\tClean up everything"

list:
	{% for container in containers %}
	@echo -e "{{container.name}}{% if container.pod %} ({{container.pod}}){% endif %}: {{container.description}}"
	{% endfor %}
{% for pod in pods %}

pod.name:
	podman pod create --name {{pod.name}} \
	{% for container in pod.containers %}
	{% for port in container.ports %}-p {{port}} {% endfor %}
	{% endfor %}
{% endfor %}

{% for container in containers %}
{{container.name}}:{% if container.pod %} | {{container.pod}}{% endif %}
	podman create --name {{container.name}} \
	{% if container.pod %}
	--pod {{container.pod}} \
	{% endif %}
	{% unless container.pod %}
	{% for port in container.ports %}-p {{port}} {% endfor %} \
	{% endunless %}
	{% for volume in container.volumes %}
	-v {{volume}} \
	{% endfor %}
	{{container.image}}

{% endfor %}

start:
	{% for container in containers %}
	podman start {{container.name}}
	{% endfor %}

stop:
	{% for container in containers %}
	-podman stop {{container.name}}
	{% endfor %}

install:
	{% for container in containers %}
	podman generate systemd {{container.name}} > $(SERVICE_PATH)/{{container.name}}.service
	{% endfor %}

enable:
	{% for container in containers %}
	systemctl enable {{container.name}}.service
	{% endfor %}

disable:
	{% for container in containers %}
	systemctl disable {{container.name}}.service
	{% endfor %}

clean: stop disable
	{% for container in containers %}
	-podman container rm {{container.name}}
	-rm $(SERVICE_PATH)/{{container.name}}.service
	{% endfor %}
	{% for pod in pods %}
	podman pod rm {{pod.name}}
	{% endfor %}

.PHONY: all help list {{ pods | map: "name" | join: " " }} {{ containers | map: "name" | join: " "}} start stop install enable disable clean
